# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics

on:
  # Scheduled updates every 8 hours
  schedule: [{ cron: "0 */8 * * *" }]
  # Allow manual triggers and updates on pushes
  workflow_dispatch:
  push: { branches: ["master", "main"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: stalomeow/metrics@projects-v2 # lowlighter/metrics@latest
        with:
          # Authentication
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          committer_username: nullure
          committer_email: nullure@users.noreply.github.com
          output_action: push

          # Core configuration
          user: nullure
          template: classic
          base: header, activity, community, repositories, metadata

          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B

          # Language stats
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: html, css
          plugin_languages_limit: 10
          plugin_languages_sections: most-used

          # WakaTime
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs

          # Followers
          plugin_followers: yes
          plugin_followers_limit: 10

          # Repositories activity and contributions
          plugin_repositories: yes
          plugin_repositories_featured: CaviraOSS/OpenMemory, CaviraOSS/pagelm, CaviraOSS/OpenReason, CaviraOSS/SecuPrompt
          plugin_repositories_affiliations: owner, collaborator, organization_member
          plugin_repositories_forks: false

          # Lines of code & code review
          plugin_lines: yes
          plugin_lines_sections: repositories, history
          plugin_lines_repositories_limit: 5

          # Activity overview
          plugin_activity: yes
          plugin_activity_limit: 10
          plugin_activity_days: 14
          plugin_activity_filter: all

          # Calendar
          plugin_calendar: yes
          plugin_calendar_limit: 1
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
